### ISSUE TITLE
Checklist for deep dive episode processing

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#100]
Creating a template issue for processing and releasing deep dives.

## Acceptance

* [ ] make page stub, generate URL for episode
* [ ] Write blurb
* [ ] Draft image
* [ ] Upload youtube
    * [ ] Link page from youtube notes
* [ ] Upload to anchor
* [ ] (can be later) add show notes in raw form

Release

* [ ] Make youtube public
* [ ] Add youtube public link to 

Extras

* [ ] Tidy show notes

**Comment by nathenf** [comment]
@rufuspollock I think this is the same as https://github.com/life-itself/comms/issues/30
