### ISSUE TITLE
Editor guide

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#103]
Guide for people contributing content or managing contribution of content.

## Acceptance

* [ ] `/meta/guide` exists
* [ ] has basic instructions for editing the site

## Tasks

* [ ] Introduction: Explain how site works and how you can edit
	  * [ ] Wiki-like with sections
		  * [ ] Technical architecture (?)
	  * [ ] Use markdown
	  * [ ] Editing
		    * [ ]  Edit direct on github
		    * [ ] (More sophisticated) clone the repo and edit locally (using obsidian)
* [ ] Markdown: this section introduces you to markdown. Already done here so can reference https://playbook.datopian.com/markdown/ 
* [ ] Frontmatter: briefly explain what is frontmatter and why it is useful (look up in Obsidian info?)
* [ ] Publishing flow: explain how the site gets published - mostly useful for developers but helps editors understand how stuff goes from github to the site
	  * Github
	  * Obsidian - our default editor. Markdown plus wiki stuff

**Comment by sdiehl** [comment]
Right now I'm just distributing .docx files to other academics. But it would be great if we could onboard people onto the Obsidian workflow. I can write up a quick intro but even Edit on Github is still probably slightly above the level of most of the people I would target for feedback though. Not sure how to get around this but open to ideas.

**Comment by EilidhRoss1** [comment]
@catherinet1 will be taking on this task. I have handed it over and she is fully briefed on what is needing done, and the progress that has already been made. Catherine, I've uploaded the video tutorial Khalil and I recorded to the google drive. Here's the [link](https://drive.google.com/file/d/1mWqXDx6ICJ_1qreoYoB774weWi-AtyDo/view?usp=sharing)

**Comment by catherinet1** [comment]
Updated issue so that @EilidhRoss1 knows current status of editor guide draft while I am away.

**Comment by catherinet1** [comment]
@khalilcodes Please could you review the few sections highlighted in green in this [draft](https://docs.google.com/document/d/1RcwjaJYn0jtMw9rOR9W0Gv2fmQDd7Fjr53NM6j1-lco/edit#) of the editor guide to check they are correct and add any clarifying comments? They are some more technical bits which I researched myself so would value them being checked by someone with more technical experience.

**Comment by catherinet1** [comment]
FIXED. Editor guide completed and linked on website.

**Comment by rufuspollock** [comment]
@catherinet1 would encourage in the FIXED comment to actually link to the guide. Otherwise i get the notification and have to dig around in the issue and/or site in order to find the guide and review it.

Also acceptance criteria aren't updated - cf https://tao.lifeitself.us/issues/#completing-tasks (e.g. a brief comment on what are the brief editing instructions or even direct link to the section in the guide would be great)
