### ISSUE TITLE
Deep Dive episode 5: incremental financial innovation 

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/web3#107]
## Acceptance 

- [x] Rufus and Stephen have been updated that conversation is ready to be published on YouTube and Anchor. ✅  
- [x] Page stub has been made and URL generated ✅  https://web3.lifeitself.us/notes/fintech-incrementalism-and-responsible-innovation 
- [x] Conversation published on Youtube & Anchor ✅   **[Youtube](https://www.youtube.com/watch?v=7rLQoTtwRSU&ab_channel=LifeItself)** **[Anchor](https://anchor.fm/life-itself/episodes/Fintech-Incrementalism-and-Responsible-Innovation-e1gn02u/a-a7gpq18)**
- [x] Secondary Content and Direct links shared on Social Media ✅ 

## Tasks

- [x] Duplicate this Template and rename as the working title of the conversation
- [ ] Create a new folder for the conversation here: TBC **we need to link up on file storage**
- [x] Source the video file and transcript from the conversation and add to folder
- [ ] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes. Add this to folder.
- [x] **Create Youtube video**
  - [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE0jpVGmYc/ZqHVHrVNiniCS83nr4JjfQ/view?utm_content=DAE0jpVGmYc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview).
  - [x] Edit the video file in VN Editor:
    - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
    - [x] Add thumbnail at the beginning of the video with a fade transition to the video
    - [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute 
    - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
    - [x] Increase the sound volume as much as possible without clipping the sound (you will notice because it will sound bad) 
  - [x] Export as Video and also Audio only
  - [x] Upload to Youtube: Add title, thumbnail, summary, page stub URL, add to Web3 playlist, Add Language, Make License Creative Commons.
  - [x] Notes from the conversation are on the webpage for that conversation.
    - [x] Notes are complete, comprehensive and tidied
  - [x] Inform Rufus and Stephen that youtube video is ready to go.
  - [x] Publish
  - [x] Ensure Rufus and Stephen tweet about video
- [x] **Create Podcast**
  - [x] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [x] Add title & summary (incl page URL)
  - [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE54jmAtvg/WrhRg3ZXky9HGlM_wSFvDA/view?utm_content=DAE54jmAtvg&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [x] Add season number and episode number
- [x] **Create Secondary Content**
  - [x] Cut the video excerpts from the main video
  - [x] For reels, change the video for to 4:5 and the Canvas to 9:16 - [Add this as a the background](https://www.canva.com/design/DAE5tHBDipU/1xYtzxMaw9I6qt6EWnYJPA/view?utm_content=DAE5tHBDipU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [x] Reduce video saturation to -100
  - [x] Write subtitles overlay to go above the video on the background
  - [x] Create Reel Cover using [this template](https://www.canva.com/design/DAE5tHBDipU/1xYtzxMaw9I6qt6EWnYJPA/view?utm_content=DAE5tHBDipU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [x] For Twitter Keep the video excerpt as 16:9 format and add subtitles to the top of the video
  - [x] Create Quote posts using [this template](https://www.canva.com/design/DAE55uh2UYk/ej7oANpJqsO5-0rWq2at1Q/view?utm_content=DAE55uh2UYk&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [x] Add all content to the folder that has been created 
- [ ] **Create Blog Post**
  - [ ] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript
  - [ ] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript
- [ ] Compile all the information in the [Web3 Spreadsheet](https://docs.google.com/spreadsheets/d/12Yh1kuxH4uoposLUJsJifM2W_zixkAhlc7QgcKavfls/edit#gid=2377395)

**Once blog is complete we can schedule content on Twitter, FB and IG**

**Comment by rufuspollock** [comment]
@EilidhRoss1 changed title here - note i would refer to these sessions under the general title "deep dives".

**Comment by EilidhRoss1** [comment]
FIXED. Deep dive ep 5 fully processed and published

**Comment by EilidhRoss1** [comment]
FIXED. Deep dive ep 5 fully processed and published
