### ISSUE TITLE
Frontmatter for deep dive pages - including editor instructions

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#114]
Let’s store “structured” content for page in frontmatter e.g. image, description etc so that …

* can do SEO tags for the page – these are pages where we have a specific description, image etc
* can pull this info into the front page “Latest Releases”
* can showcase this on a “deep dives” page

## Acceptance

* [x] Refactor one deep dive page to use frontmatter **@`notes/neo-metallism.md`**
* ~~[ ] Document these fields in editing guide~~ Moved to #103 
* [x] Create a template for deep dive pages  **@ `./templates/template.md`** 
* [x] Refactor all deep dive pages
     *commits (2022/04/22):*
     - [notes/are-crypto-tokens-securities.md](https://github.com/life-itself/web3/commit/9c29a370070cc03ad29179f55bca092e785ae85d#diff-507bec1c0c4cb857f0c673fc1b4dc28ba58c4a66e5e385c57905a80e9e338de7)
     - [notes/collective-action-problems-and-climate-change.md](https://github.com/life-itself/web3/commit/e3a93e390837b4a2cfc1dad561e401ad8ae2828e#diff-160973d96c877e4b120e4904321bdcf2038424873cb4018d0d8727342d1b0c58)
     - [notes/fintech-incrementalism-and-responsible-innovation.md](https://github.com/life-itself/web3/commit/e0f32a20f6809ebcc62aa100e5b6369823e7930f#diff-7ba240f2f4ef298b121a30e036abcbe28661891e28e44098b9960938b36afe4c)
     - [notes/market-fundamentalism.md](https://github.com/life-itself/web3/commit/171aeddf76a813008d3a7d60c437c5f336c07f6c#diff-6683c9d355b051f585ee0bda8c22f0292d2d52f8cdc4bdbc39535018d2520754)
     - [notes/post-state-technocracy.md](https://github.com/life-itself/web3/commit/82e589e342d5b3b1244c3ba8e43d7b983468f818#diff-44fcbd3f261e6bc4be10632db02e39a10748e7d47c62705d702b338bc313700d)

## Tasks

* [x] Refactor one page to use frontmatter
  * [x] Identify key frontmatter fields
     - key fields: title, date (published), description, (youtube, podcasts although can be left out)
     - other fields: image (thumbnail) and featured (defaulted to false), created, aliases
  * [x] Update MDX component page template to display those fields if present
  * [x] Add SEO based on the frontmatter fields
     - title, description and Image
* [x] Create a template for creating / editing deep dive pages 
   - 'templates/'  folder in root web3 for Obsidian
* [x] Update contentlayer to support these fields

Editor guide

* [x] create a template for these pages - BONUS: obsidian templates

### Key front matter fields

Required for deep dive

* title
* date: publication date
* description
* image
* featured: `true` - this will be used to determine whether featured on Latest Releases on front page

Optional ... (to be decided if we use these - if we have them all the time we could have a standard layout for these pages)

* youtube
* podcast

Note standard fields:

* created: date *this* page in wiki was created (so more internal housekeeping)
* aliases: obsidian field for aliasing pages

**Comment by EilidhRoss1** [comment]
@catherinet1 I've assigned you to this task as it's relevant to the editors' guide.

**Comment by rufuspollock** [comment]
@khalilcodes pretty much all done on tech side. What i suggest is you and @EilidhRoss1 go through late next week and update the deep dive pages and add info to editing guide (reassigning to you @EilidhRoss1 as relates to the deep dive pages which you are maintaining)

**Comment by khalilcodes** [comment]
Moving 'Document fields in editing guide' to #103 and closing issue.
