### ISSUE TITLE
Processing Rufus & Cory Doctorow Conversation

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#122]
Rufus has recorded a conversation with Cory Doctorow and shared with Comms Team via email. This should be added to our processing backlog for web3 conversations.

## Acceptance

- [ ] Conversation is uploaded to podcast platforms
- [ ] Conversation is listed on web3 site
- [ ] (Optional) Conversation is uploaded to YouTube

## Tasks
...

**Comment by EilidhRoss1** [comment]
FIXED

**Comment by rufuspollock** [comment]
@EilidhRoss1 when closing stuff can we follow the guidelines on https://tao.lifeitself.us/issues/#closing-issues - at minimum would expect some link to the notes page on the web3 site plus the acceptance section updated.

**Comment by EilidhRoss1** [comment]
@rufuspollock Nathen and I have been using a template for issues for processing conversations, the Cory Doctorow issue in line with that template can be found here https://github.com/life-itself/comms/issues/47 . That issue was closed in line with the guidelines at the time I finished the task. This issue was created by Theo when he was not aware that we already had an issue in place for the task. I closed this issue last week when I was just tidying up my outstanding github issues. I should have commented that it was a duplicate of a task that had already been done and where to find the detailed issue. Apologies.
