### ISSUE TITLE
Resolve build errors related to git lfs asset

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#125]
Yesterday i added an image file in assets folder and it seems to have broken the build:

```
2:01:55 PM: Error checking out branch: Downloading assets/Pasted image 20220313211349.png (589 KB)
Error downloading object: assets/Pasted image 20220313211349.png (1c32373): Smudge error: Error downloading assets/Pasted image 20220313211349.png (1c32373eb2b436d57147edc5e18f8d3b48c8f93cce3dbc07ef19b48886c0461b): batch request: missing protocol: ""
```

## Acceptance

 * [x] Build working again
 * [x] BONUS: source of error identified so we avoid in future **FIXED. enable git lfs by setting env variable `GIT_LFS_ENABLED` to `true` (in UI)

## Tasks

* [x] Try to fix the error one way or the other

**Comment by rufuspollock** [comment]
OK, my best guess is we just need to enable git lfs on netlify ...

https://answers.netlify.com/t/builds-fail-after-new-commit-to-git-lfs/1362/4

> If cloning a repository using LFS, we recommend using an environment variable GIT_LFS_ENABLED in our documentation [here 110](https://www.netlify.com/docs/build-settings/#additional-variables-that-can-affect-the-build). Quoting:
> 
> If you set a GIT_LFS_ENABLED variable, we’ll use git lfs clone to check out your repository — otherwise we just use git clone .

**Comment by rufuspollock** [comment]
FIXED. See above.
