### ISSUE TITLE
Latest Releases on homepage from frontmatter

### ISSUE THREAD

**Issue by khalilcodes** [life-itself/web3#136]
Latest releases section on the homepage to display videos from pages in frontmatter 

## Acceptance:

* [x] Latest releases list based on frontmatter `featured: true` in *date order* with most recent first
* [x] Cards with following info:
     - title
     - description
     - image
     - link to webpage for that "post/note"

## Tasks:

* [x] Refactor latest releases section to display list of featured
* [x] Update pages (currently featured on homepage) with required frontmatter

## UPDATE:
**Since latest releases are basically featured blog posts / pages, it's not required to restructure frontmatter as stated below. Content should be the same.**

## Notes:
**Disregard. see update above**
Following are the **BLOCKERS** to be addressed

- title (page title and card title do not match ??)
- description (page description and card description are different ??)
- some pages may not need a youtube video on them (add separate boolean field to display on page ??)

Possible solution would be to convert the youtube field to a nested field in frontmatter with the above info. *see below for eg.*
```
// page frontmatter ...
---
title: ...
description: ...
youtube:
  - title: ...
  - link: ...
  - descritption: ...
  - image: ...
  - featured: true (on homepage)
  - page: false (display on this page ?)
---
```

**Comment by khalilcodes** [comment]
@rufuspollock please review above for frontmatter restructure

**Comment by rufuspollock** [comment]
@khalilcodes we don't need youtube link as we should link to the webpage for that post not youtube.

**Comment by rufuspollock** [comment]
@khalilcodes i've also updated acceptance
