### ISSUE TITLE
Making Notes Accessible from Homepage

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#140]
When I'm exploring the web3 site I want an easy way to access notes pages without knowing/entering page URLs.

## Acceptance

- [ ] Mains site menu has a navigation function to explore notes pages

## Tasks

- [x] Add a link to notes page in navbar
- [x] Create a notes page featuring all notes

### Notes

- Some of the notes pages do not have frontmatter and so they are not included in the list. To include them, adding frontmatter is required.
- Adding images is considered essential to keep a consistent layout for all cards.

**Comment by theo-cox** [comment]
Hey @olarubaj I see there's been some great work done via the other issue, however it still seems that not all notes are visible via menu/clicks alone. As we are now transitioning this project, this is one of the last priority areas for us so would you or @khalilcodes mind picking it up? Thanks so much!

**Comment by theo-cox** [comment]
FIXED. There is now a central notes page which will shortly update with all notes, upon completion of #187

**Comment by rufuspollock** [comment]
@khalilcodes @theo-cox i think we now agree there was prob miscommunication here as we already had the `/all` page. Personally i would suggest we link "notes" in navbar to that page for now and can leave `/notes/` as an orphan (OR: and open to suggestion here: we just replace /notes/ with what is currently /all/ and redirect /all/ there for now))

**Comment by theo-cox** [comment]
Fine to follow your suggestion
