### ISSUE TITLE
various UI/UX fixes

### ISSUE THREAD

**Issue by olarubaj** [life-itself/web3#142]
## Job Story
As a user, I want to enjoy the overall experience of exploring the web3 project site and focus on making sense of crypto rather on UI/UX shortcomings 😀

## Acceptance: 
- [ ] "Latest Releases" text doesn't render on top of the image for smaller screens

![image](https://user-images.githubusercontent.com/104430201/166566935-f78a3c32-e6a5-4b1f-97a1-7d31623d3ad4.png)

- [ ] "Discover all" button for "Latest Releases" section added
- [ ] the image in "We need better sensemaking" section for smaller screens should not be duplicated

![image](https://user-images.githubusercontent.com/104430201/166570207-e61cb643-2d58-46b1-81f0-35ec11463142.png)

- [ ] make the images a bit smaller for smaller screens
- [ ] make coggle tree graphs on the About page more readable

## Tasks: 
- [ ] move the Latest Releases heading and its content below the image
- [ ] add button(s) linking to all articles/explorations under "Latest Releases" section **it seems it's already being addressed by [this issue](https://github.com/life-itself/web3/issues/140)**
- [ ] investigate and fix duplicated image in "We need better sensemaking" section
- [ ] fix image responsiveness on the home page
- [ ] add links to coggle graphs for trees on the "About" page
