### ISSUE TITLE
Tweet link shows a preview/embed

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#150]
Like we do with youtube ... #88 

## Acceptance

* [x] Tweet component ... **DONE** components/TwitterEmbed.js
* [x] Pasting a twitter link in its own paragraph at line start results in embed e.g. pasting the following results in an embed/preview of the tweet **DONE** *see /test page or screenshot below*

```
Blah, blah ...

https://twitter.com/rufuspollock/status/1524012242777395201

```

## Tasks:
- [x] create a tweet embed component
    - with placeholder for loading and deleted/not found tweets
- [x] add custom styles for proper tweet embed previews (dark mode)
- [x] use component in links for parsing in markdown.

## Screenshot

![deploy-preview-161--boring-fermat-22cb64 netlify 1](https://user-images.githubusercontent.com/42637597/173255720-a6e2963b-8278-4ed2-a465-b778d7213290.png)

## Notes:
- Twitter embed api is fairly slow and so takes time to load. A placeholder has been added for better ux.
- On further research during development, the embeds (youtube, twitter, etc) load iframes with large htmls which affect the page load and SEO.
- Possible solutions to the above problems:
     -  fetch tweets and render component during build time. This requires getting a twitter api key and recreating custom twitter component that matches the look of the embed. (overwork but blazing fast. see [here](https://static-tweet.vercel.app/)).
     - create remark plugin for twitter embeds based on this [gatsby remark plugin](https://github.com/octahedroid/gatsby-remark-twitter/blob/master/index.js). Although still not sure if this would resolve tweet loading time.
