### ISSUE TITLE
Set home page social preview image as default for all pages

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#155]
Configure the SEO stuff so that the social preview image (`og:image` i think) defaults to:

* frontmatter `image` attribute if set
* the default social preview image (the one for the home page which is set in `siteConfig.js`

## Acceptance

Currently e.g. yields nothing whilst https://socialsharepreview.com/?url=https://web3.lifeitself.us/ works.

Also this one which should have a frontmatter image  shows nothing.

* [x] https://socialsharepreview.com/?url=https://web3.lifeitself.us/guide  and any other page without frontmatter image) shows the default social preview (i.e. one of the home page) **Done see tasks below**
* [x] https://socialsharepreview.com/?url=https://web3.lifeitself.us/notes/are-crypto-tokens-securities and other deep dive pages (which should have a frontmatter image ...) show that image **Done see tasks below**

## Tasks

* [x] All other Pages without frontmatter `image` shows default social preview of homepage (siteconfig)
* [x] Deep dive pages -
   * [x] pages with frontmatter `image` for social preview
   * [x] pages without frontmatter `image` but with `youtube` shows youtube thumbnail image
       - src for image is `https://img.youtube.com/vi/<youtube-video-id>/maxresdefault.jpg`
   * [x] defaults to homepage image if no frontmatter `image` and/or `youtube` is set

**Comment by rufuspollock** [comment]
@khalilcodes you have marked as closed but https://socialsharepreview.com/?url=https://web3.lifeitself.us/notes/are-crypto-tokens-securities and there is no image showing up. Does it work for you?

**Comment by khalilcodes** [comment]
@rufuspollock it's working on my end. Not sure, maybe socialshare sometimes doesn't detect as it didn't show up on first try ...

<img style="max-width:300px" src="https://user-images.githubusercontent.com/42637597/169579626-fe623cae-2589-4448-89f6-3902bcfbe65e.png" />

**Comment by rufuspollock** [comment]
@khalilcodes great - so let's assume it works! (Worth noting things like you tried it in both places in acceptance (next time) -- v useful info).
