### ISSUE TITLE
Optimize SEO for Angela Walch Summary

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/web3#164]
We want someone googling 'Is crypto / web3 decentralized?', 'How is crypto / web3 decentralized?' 'what is decentralization?' to come across [our summary](https://web3.lifeitself.us/notes/deconstructing-decentralization) of Walch's 'Deconstructing 'Decentralization': Exploring the Core Claim of Crypto Systems'. SEO for this page should be optimized so as to achieve this.

## Acceptance

- [x] On-page SEO optimized - @EilidhRoss1 **[Nathen, can you check](https://web3.lifeitself.us/notes/deconstructing-decentralization)**
  - [x]  Metadiscription
  - [x] Headings framed as questions, immediately followed by 2 sentence answer in bold. 
- [ ] Technical SEO optimized - @khalilcodes @olayway 
  - [x] Page load speed, *see metrics below*
  - [ ] Google search console, *? is this for analysis.*
  - [x] site map *found at web3.lifeitelf.us/sitemap.xml*

## Tasks

- [x] Page SEO:
    - [x] `keywords` field in frontmatter (for keyword topics and article tags)
         - usage:
            ```javascript
            ---
            ...
            keywords: "example 1, example 2, etc.."
            ---
            ```
         - This will add meta for "keywords" and "article tags"
    - [x] Sitemap script on build
- [x] Page speed optimization:
    - [x] Replace youtube embeds - [react-youtube-lite-emebed](https://github.com/ibrahimcesar/react-lite-youtube-embed)
    - [x] Properly size images
    - [x] Remove podcast embeds and replace with a link instead
    - [x] dynamic imports of components (code-splitting)
    - [x] Site cleanup: unused packages in `package.json` and dev dependencies

## Notes:

*Based on SEO research, meta keywords are not crawled by google but bing and yahoo do. Therefore, keywords are also being used in meta article tags and so can be used to include authors and topics related to the article.*

## Metrics:

- *Using [GTmetrix](https://gtmetrix.com/) the following difference can be seen in performance.*
- *note that fully loaded times and seo will differ on preview deploys as third party netlify scripts are being run and also those pages are not indexed for seo. Expecting page performance at 100% and reduced loaded time to approx ~1.5s*

**CURRENT:**
- For [notes/are-crypto-tokens-securities](https://web3.lifeitself.us/notes/are-crypto-tokens-securities)
   - summary:
      <img src="https://user-images.githubusercontent.com/42637597/171623816-74f796a1-8e24-4995-bbe7-a7d4b4f741fe.png" height="250" />
   - page size:
     <img src="https://user-images.githubusercontent.com/42637597/171625210-7895b346-b48c-46d0-bca5-aa585ed10ebf.png" height="200" />

**NEW:**
- On preview deploy for [notes/are-crypto-tokens-securities](https://deploy-preview-169--boring-fermat-22cb64.netlify.app/notes/are-crypto-tokens-securities) 
   - **summary**: *grade and web vitals improved from previous.*
     <img src="https://user-images.githubusercontent.com/42637597/171625443-a041c7b2-509b-4a1c-a97b-8909e6ab4f85.png" height="250" />
   - **page size**: *page size has been decreased to 1.17mb from 6.3mb previously*
     <img src="https://user-images.githubusercontent.com/42637597/171625587-09bcd961-097e-4766-8911-d6f2d72f0e51.png" height="200" />

**Comment by EilidhRoss1** [comment]
@khalilcodes @olayway discussed this with @nathenf. He says there are two aspects of the SEO we can optimize: on-page SEO and technical SEO. Can you look into the technical stuff: Page load speed, Google search console, site map. Re the on-page stuff, we will deal with most of that but we were wondering if the pages on the web3 site have metadiscriptions (like they would if we were using wordpress?). If so, we need to make sure our pages have metadiscriptions.

**Comment by EilidhRoss1** [comment]
@khalilcodes @nathenf can we close this?

**Comment by EilidhRoss1** [comment]
@khalilcodes @nathenf just following up, can this be closed?

**Comment by nathenf** [comment]
FIXED - Webspeed optimized and SEO optimized
