### ISSUE TITLE
Extract video segment on Gold Fever from Sebastiao Salgado documentary

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#183]
Amazing segment from Sebastiao Salgado on gold fever, see:

https://web3.lifeitself.us/notes/sebastiao-salgado-gold-fever-salt-of-the-earth

Want to extract of the precise segment on gold fever from overall document and upload on Life Itself Youtube so we can embed (starts at 04:48 and follows the transcript that is in the note 

## Acceptance

* [ ] Understood task
* [ ] Extracted the few minute segment from archive.org video
* [ ] Uploaded to Life Itself channel
* [ ] Embedded into the note
* [ ] Shared on social media

## Tasks

TODO
