### ISSUE TITLE
[inbox] Transcribing episodes / interviews

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#195]
Transcribe and publish each of our episodes e.g. https://web3.lifeitself.us/notes/samer-hassan

For each of our interviews we can publish a proof-edited transcript so that content is readable (not just listenable) and e.g. annotable, linkable, reusable (in others parts of wiki)

* Probably don't need this for episodes like deep dives with extensive notes

Process:

* [ ] Do an automated transcription with Otter
* [ ] Hackmd or similar and proof edit (or just publish direct and then do the tidying)
* [ ] Proof-edit
* [ ] Sign-off
* [ ] Publish

## Tasks

* [ ]  Prep
  * [ ] List all the interviews (that require transcribing) - see the front page for a list
  * [ ] Prioritize
* [ ] For each episode do the process above ...
  * [ ] ...
  * [ ] https://web3.lifeitself.us/notes/samer-hassan

### https://web3.lifeitself.us/notes/samer-hassan

* [ ] Do an automated transcription with Otter
* [ ] Hackmd or similar and proof edit (or just publish direct and then do the tidying)
* [ ] Proof-edit
* [ ] Sign-off
* [ ] Publish
