### ISSUE TITLE
Standard structure for claims

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#196]
When creating a claim page I want to know how to structure so i am assisted in my writing and have correct info

## Acceptance

- Standard structure for thesis and evaluation
- Standardize structure for frontmatter
- Referencing for claims

## Tasks

* [x] lay out analytical structure
* [x] set out frontmatter structure
* [ ] references
  * [x] structure
  * [ ] process of importing back into obsidian from zotero - see e.g.   - Can export into obsidan via zotero bib method https://medium.com/@alexandraphelan/an-academic-workflow-zotero-obsidian-56bf918d51ab

### Standard structure of analysis

*NB: This is a suggestion not a strait-jacket 😄*

- [ ] X is desirable (may have subclaims)
- [ ] Crypto/web3/blockchain will provide X
  - [ ] and better than alternatives
- [ ] No side effects that outweigh benefit of X

All 3 need to be true/plausible for claim to be overall true/plausible.

### Frontmatter

Purpose:

* [ ] Can find all the claims (automatically)
* [ ] Can find all deep dives
* [ ] Can find all featured
* [ ] Can find all interviews
* [ ] For each claim
  * [ ] have title
  * [ ] BONUS have description
  * [ ] evaluation
* [ ] Make clear method for logging evidence for claims being made
  * [ ] Basic option: add to zotero with note
  * [ ] More advanced: do basic *and* create a notes page for that article with excerpts
* [ ] Show evidence for claims
  * [ ] Blockquote with citation/link
    * [ ] If we have a dedicated page for that person/author then link them instead (?)

Other front matter

* [ ] title
* [ ] description

```md!
title:
description: # optional (can fill in later)
category:
  - claim: y
  # and also optional (default is n)
  - featured: y # optional
  - interview: y
  - deepdive: y
claim:
  - evaluation: # options? YY, Y, ?, N, NN
  - confidence: # hh, h, m, l, ll (very high to medium to very low)
```

### Reference process

- Let's have a folder per claim in zotero
  - Add all references there
  - Have a subfolder for "Evidence Claim being Made"
