### ISSUE TITLE
Convert editor guide into markdown and publish on site

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#197]
merge gdoc content linked from https://web3.lifeitself.us/meta/editing into the site

Why convert from google docs?

- consistent with rest of the site
- Can edit in standard way via pull requests
- consistent styling
- one less click
- can link to other parts of site using standard obsidian style
- will reuse on other projects

## Acceptance

* [x] Guide is all on site ✅ https://web3.lifeitself.org/meta/editing 
* [x] GDoc is deprecated/deleted

## Tasks

* [ ] Transfer editing guide onto site ✅ **🚧 commit: https://github.com/life-itself/web3/commit/885449e12fc28efb2ffcd06ce1dbc2841bc4c646**

**Comment by EilidhRoss1** [comment]
FIXED guide is published: [https://web3.lifeitself.org/meta/editing](https://web3.lifeitself.org/meta/editing)
