### ISSUE TITLE
Reflections on Crypto Post FTX collapse with Stephen Diehl

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/web3#210]
Publish latest episode with Stephen Diehl: "Reflections on Crypto Post FTX collapse"

## **Acceptance**

- [x] Rufus and Stephen have been updated that conversation is ready to be published on YouTube and Anchor.
- [x] Page stub has been made and URL generated ✅ **[Published 15/11/22](https://web3.lifeitself.org/notes/post-ftx-collapse)**
- [x] Conversation published on Youtube & Anchor ✅ **Published 15/11/22 on [YouTube](https://www.youtube.com/watch?v=ApxGyyCbYpM&ab_channel=LifeItself) and [Anchor](https://spotifyanchor-web.app.link/e/mNcbxAaLYub)**
- [x] Secondary Content and Direct links shared on Social Media

## **Tasks**

- [x] Duplicate this Template and rename as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) ✅ **https://drive.google.com/drive/folders/1G1lNIjRkiLu_XXtv2R7EaNoJIKFb-kmD** 
- [x] Source the video file and transcript from the conversation and add to folder ✅ **Both in folder**
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder.
- [x] Create Youtube video ✅ https://www.youtube.com/watch?v=ApxGyyCbYpM&t=1s&ab_channel=LifeItself 
  - [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
  - [x] Edit the video file in Da Vinci Resolve:
  - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
  - [x] Add thumbnail at the beginning of the video with a fade transition to the video
  - [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
  - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
  - [x] Increase the sound volume as much as possible without clipping the sound (you will notice because it will sound bad)
  - [x] Export as Video for Youtube
  - [x] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to Web3 playlist, Add Language, Make License Creative Commons.
- [x] Notes from the conversation are on the webpage for that conversation. ✅ https://web3.lifeitself.org/notes/post-ftx-collapse 
  - [x] Notes are complete, comprehensive and tidied
  - [x] Inform Rufus and Guest that youtube video is ready to go.
  - [x] Publish
  - [ ] Ensure Rufus & Guest tweet about video (for web3)
  - [ ] Share on Insta stories
- [x] Create Podcast ✅ https://anchor.fm/life-itself/episodes/Post-FTX-collapse-reflections-on-crypto-with-Stephen-Diehl-e1qpu04 
  - [x] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [x] Add title & summary (incl page URL)
  - [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [x] Add season number and episode number
  - [x] Publish
  - [x] Inform Rufus and Stephen (for web3)
  - [ ] Share on Insta stories
- [ ] Create Secondary Content
  - [ ] Cut the video excerpts from the main video and leave all the clips in one timeline \
  - [ ] Export just the audio \
  - [ ] Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai \
  - [ ] Upload the srt file to the project \
  - [ ] Crop top and bottom of video - add title to top and subtitles at the bottom
  - [ ] Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
  - [ ] Add all content to the folder that has been created
- [ ] Create Blog Post
  - [ ] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript
  - [ ] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript
  - [ ] Compile all the information in the [Web3 Spreadsheet](https://docs.google.com/spreadsheets/d/12Yh1kuxH4uoposLUJsJifM2W_zixkAhlc7QgcKavfls/edit#gid=2377395)
  - [x] Send email to "Web3" mailing list on Mailchimp

Once blog is complete we can schedule content on Twitter

**Comment by EilidhRoss1** [comment]
FIXED

- [x] Rufus and Stephen have been updated that conversation is ready to be published on YouTube and Anchor.
- [x] Page stub has been made and URL generated ✅ **[Published 15/11/22](https://web3.lifeitself.org/notes/post-ftx-collapse)**
- [x] Conversation published on Youtube & Anchor ✅ **Published 15/11/22 on [YouTube](https://www.youtube.com/watch?v=ApxGyyCbYpM&ab_channel=LifeItself) and [Anchor](https://spotifyanchor-web.app.link/e/mNcbxAaLYub)**
- [x] Secondary Content and Direct links shared on Social Media
