### ISSUE TITLE
Web3 Guide Launch

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#214]
Up to 5 person days to spend officially launching and publicizing the finalised Web3 guide (which we put a lot of effort into!).

Aiming to launch late Feb-early March

https://web3.lifeitself.org/guide

**[Web3 Launch Folder](https://drive.google.com/drive/folders/1gQx7owQSNo06nUJ1fehV07rodiO9j00Z)**

## Acceptance

- [x] Guide pre-shared with friendly contacts for review
- [x] Launch plan and content created
- [x] Engagement targets set ✅ **Get featured on 2-5 podcasts, get featured on some external websites, increase viewership on the website to 500 monthly users**
- [x] Launch delivered ✅ **Posted across socials, got interviewed on the Future Squared Podcast, with Scam Economy Podcast in the pipeline. Ongoing outreach with podcasts and places to get featured.**

## Tasks

- [x] Theo and Nathen planning meeting
- [x] Roadmap/strategy created
	- [x] What content do we want? ✅ **Consistent messaging across platforms with low-cost efforts. Focus more on the network effect of dissemination rather than creating lots of content.**
	- [x] List of locations to post ✅ **post on our platforms and hit major media outlets, niche podcasts and drop into the DMs of interested folk**
	- [x] List of people to engage directly 🚧 **[Web3 Network Database](https://docs.google.com/spreadsheets/d/1_wP9S_K8pubWlmKQ6blzw0HjVeVcdBRPIHzbIAG57m0/edit#gid=0)**
- [x] Build list of media outlets and podcasts to feature on 🚧 **Also in the database**
- [x] Launch content created
    - [x] Announce post ✅  **[Blog post](https://docs.google.com/document/d/1JsZnt6UpMKpKLM2rxC0vMjbxSE24hjy3Th1yVFgbq4w/edit#)**
    - [x] Tweets ✅ **[Email & Social Content](https://docs.google.com/document/d/1TXIg3LFsSAASfoPxYm3A3-m1sZm3xFMcn4Czfl-wQJc/edit#)**
    - [x] Mailout to signup list ✅ 
    - [x] Media Kit for people to share ✅ **[Sharing Kit](https://docs.google.com/document/d/1kJvfoS8PT0eBBGIzb1AxdPb8MvTfKsplq_-uB8Gik78/edit?usp=sharing)**
    - [x] Press release ✅  **[Web3 Guide Press Release](https://docs.google.com/document/d/1Xi0_V3Q0vhOfYBk6XW342tw3OvsU8hSNNjXapT-gOCw/edit)**
    - [x] Podcast Pitch ✅ **[Pitch](https://docs.google.com/document/d/1uMXX68VABcoumwbQ97Bh-RyBTp-pF_-wfqP6CL22cOs/edit)**
- [x] Guide shared with Stephen Diehl for review
- [x] Guide shared with Stephen Reid
- [x] Initial social media launch
  - [x] Posts sent out on Instagram, Facebook and Instagram ✅ **all posts sent out on 2nd March, 2023**
  - [x] Blog post made and added to general newsletter ✅ **https://mailchi.mp/ae8c312625d0/kicking-off-2022-with-lots-of-action-15509229**
  - [x] Engagement with everyone who came on podcast for retweets ✅ **reached out to everyone I could but received very little response.**

## Inbox
- [Web3 guide launch planning](https://docs.google.com/document/d/1YityXUN4i1NYYVfis0FiM8eQsF7js5zS-fYosuI2kA0/edit#heading=h.1500lg6r5f1f)
- [Unfinished blog post](https://docs.google.com/document/d/1rKmCM3khJk0XNbsixVKcfE8C8gFr5QIh4Z42iRWRsFY/edit#heading=h.b9imhdunokus)
- [Another plan?](https://docs.google.com/document/d/1GVqvVvskuaiPRAg2U_ETPRF_1hcfDHOJMi_Q4wNK2_Y/edit#heading=h.d17ykeefhhl6)

**Comment by rufuspollock** [comment]
Clarifying from meeting with @nathenf on 9 Feb

- Budget: 2-3d from nathen (~1-2d from theo) => ~5d budget for marketing web3 guide etc.

**Comment by rufuspollock** [comment]
@nathenf what's remaining on this for this to be done? To me it looks like acceptance criteria are met.

**Comment by nathenf** [comment]
FIXED - We did the launch, but lacked engagement from previous participants in the projects. We were featured on the Future Squared Podcast and upcoming Scam Economy Podcast. Monthly users current stand at 459.

**Comment by nathenf** [comment]
@theo-cox @ZybN I just added my actual hours in here but perhaps you can add yours on top?

**Comment by rufuspollock** [comment]
@nathenf my big tip here for engagement would be to post both the guide and individuals items on relevant fora e.g. reddit, hackernews and other platforms with interest in web3 etc.

**Comment by nathenf** [comment]
@rufuspollock is this tip to then keep going with comms with Web3? Do you have profiles for these platforms? From my experience (which is once trying to use Reddit) if you just join and make a post it falls flat and requires building rapport before plugging yourself. Shouldn't be an issue if you have active accounts.

**Comment by rufuspollock** [comment]
> @rufuspollock is this tip to then keep going with comms with Web3? Do you have profiles for these platforms? From my experience (which is once trying to use Reddit) if you just join and make a post it falls flat and requires building rapport before plugging yourself. Shouldn't be an issue if you have active accounts.

Yes, i have an account there - and you can still post things with low karma and they still get attention. Yes, more karma better but if decent quality you get something and what we have is good quality.
