### ISSUE TITLE
Interview on Future Squared Podcast with Steve Glaveski

### ISSUE THREAD

**Issue by nathenf** [life-itself/web3#215]
[Podcast Landing Page] (https://www.steveglaveski.com/podcast-show/future-squared) 

## Acceptance

- [ ] Podcast Recorded and Published
- [ ] Podcast Shared via our media streams

## Tasks 

- [ ] Book a recording time calendly.com/steveglaveski/60minpod **Please book for after 22 Feb.**
- [ ] Announce in newsletter
- [ ] announce on Twitter
- [ ] add to a blog on our website
- [ ] retweet any ancillary content (clips, threads) that Steve creates
- [ ]  retweet from Rufus twitter account

**Comment by theo-cox** [comment]
Podcast booked for Feb 28

**Comment by rufuspollock** [comment]
@nathenf @ZybN podcast is now out. Moving to blocked until clear on next steps.

**Comment by rufuspollock** [comment]
@nathenf @ZybN if this isn't being worked on in next 24h or so let's move this to ready or blocked ...

**Comment by theo-cox** [comment]
Podcast done and recorded and uploaded here: https://open.spotify.com/episode/3kYePCxsctGCIf2VcLTg7m?si=4d801567ecf343e6
