### ISSUE TITLE
Upgrade site to use flowershow

### ISSUE THREAD

**Issue by khalilcodes** [life-itself/web3#220]
Currently this site uses an old custom setup of contentlayer with outdated packages like https://github.com/flowershow/remark-wiki-link-plus. We want to upgrade the site (and probably the overall site layout) to use [flowershow](https://github.com/datopian/flowershow) since that has upgraded features and is currently maintained.

## Acceptance

- [ ] Site uses flowershow

## Tasks

- [ ] Install latest flowershow
  - [ ] add web3 custom components (currently in `components/Home` (these are on homepage `pages/index.js`)
- [ ] modify site layout to replicate lifeitself main repo ... ? 
- [ ] ...

**Comment by tearsaalainah26** [comment]
Since Flowershow has its own built-in MDX component handling, we'll need to decide how to register
