### ISSUE TITLE
Evolve this to a more general "making sense of web3" repo / project

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#49]
## Tasks

* [x] Relocate repo to `life-itself/web3`
* [x] Update description
* [x] Update README **MOVED to #74**
* [x] Convert to have a frontend website

**Comment by sdiehl** [comment]
I started a sketch of some of the outlines and topics that are in our SCQH. Open to different structures if people have preference other than a toplevel `concepts` folder and cross-linked to other topics.

**Comment by rufuspollock** [comment]
@sdiehl i think what you have got going looks great. I've a WIP more detailed PLAN in https://github.com/life-itself/web3/blob/main/meta/plan.md

**Comment by rufuspollock** [comment]
FIXED. This happened and was launched ~3w ago. https://web3.lifeitself.us
