### ISSUE TITLE
Taxonomy for Library plus inclusion criteria

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#51]
Migrated out of #44 we have point about needing to structure the library better and to provide inclusion criteria as per this comment of @stevesong 

> Sounds good to me. I am a little concerned about the sheer volume of resources and the need to sort the wheat from the chaff. For a start it would be good to agree on a set of metatags for describing the resources. More ambitious would be some consensus on the best resources for a specific topic or best introduction to issues.

## Acceptance

* [ ] Basic taxonomy for tagging and organizing the library
* [ ] Criteria or process for adding items to the library (deciding on inclusion)

## Tasks

* [ ] Summarize the current taxonomy
* [ ] Look at SCQH and especially the issue tree and consider how that would influence a taxonomy
* [ ] v0.1 of taxonomy (and/or inclusion criteria)
* [ ] ...
