### ISSUE TITLE
Public Website v0.0.1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#53]
Initial version of an online home for the project (distinct from github itself!)

## Acceptance

* [x] Site live at web3.lifeitself.us **DONE https://web3.lifeitself.us (via cloudflare pages)**
* [x] One page site with layout roughly corresponding to [the mockup](https://github.com/life-itself/web3/blob/main/excalidraw/website-homepage-v0.1-2022-02-23.excalidraw.svg) - perhaps even just hero and latest releases (with about on about page) **✅ have a working site with hero and latest releases. Plenty more to do but can be v0.0.2**
* [x] Built with nextjs with instructions for contribution **✅ basic instructions for using in https://github.com/life-itself/web3/blob/main/site/README.md**

## Tasks

* [x] Do analysis to select online location and framework
* [x] Skeleton website in nextjs v12
* [x] Add some skeleton content and layout
* [x] Set up deployment (e.g. ~~netlify~~ cloudflare pages)

Bonus

* [x] Make site elegant and distinctive (yet reflecting Life Itself tone) @khalilcodes
	* [x] Find inspiration designs
	* [x] mockup design **IN PROGRESS https://excalidraw.com/#room=8bc8a0afb0afc89015dc,W3jd48r8_B2llA2CZ8A33A**
	* [x] design system
	* [x] implement

**Comment by rufuspollock** [comment]
FIXED. I think we have a v0.0.1. Plenty more to do and that can be next issue.

![image](https://user-images.githubusercontent.com/180658/157749396-2228a01c-248c-4a69-8755-34201d3b0b3e.png)
