### ISSUE TITLE
Content for Home Page v0.1

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/web3#62]
Create Web3 site front page

### Acceptance

- [ ] Web3 website front page published featuring copy and images found in google doc [here](https://docs.google.com/document/d/1yJobE0hBuNdHgwDmVh3KcTVcwrnC8gGQzZzsWVfNjMI/edit#) 

### Tasks

- [x] Write copy (Title, Description and CTA) ✅ **Eilidh done**
  - [x] Hero Section ✅ **Eilidh done**
  - [x] Guide ✅ **Eilidh done**
  - [x] Library✅ **Eilidh done**
  - [x] Claims ✅ **Eilidh done**
  - [x] Situation ✅ **Eilidh done**
  - [x] Problems ✅ **Eilidh done**
  - [x] Need ✅ **Eilidh done**
  - [x] Approach ✅ **Eilidh done**
  - [x] Get Involved ✅ **Eilidh done**

- [x] Collect images (svg) ✅ **Eilidh done**
  - [x] Hero Section ✅ **Eilidh done**
  - [x] Guide ✅ **Eilidh done**
  - [x] Library ✅ **Eilidh done**
  - [x] Claims ✅ **Eilidh done**
  - [x] Situation ✅ **Eilidh done**
  - [x] Problems ✅ **Eilidh done**
  - [x] Need ✅ **Eilidh done**
  - [x] Approach ✅ **Eilidh done**
  - [x] Get Involved ✅ **Eilidh done**

**Comment by EilidhRoss1** [comment]
@rufuspollock All the content for the front page (copy and links to svg images) can be found here: https://docs.google.com/document/d/1yJobE0hBuNdHgwDmVh3KcTVcwrnC8gGQzZzsWVfNjMI/edit#

**Comment by rufuspollock** [comment]
FIXED. All content is prepped. Just need to integrate which is #66
