### ISSUE TITLE
Announce v0.1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#65]
# Acceptance

* [ ] Announce posts up on Life Itself (and elsewhere)
* [ ] Blurb for sharing prepped
* [ ] Have x-posted to that annoucne
* [ ] List of places to announce in priority order
* [ ] Announced at (most) of those places
* [ ] Mailing list mailout (?)

Outcomes

* [ ] 

# Tasks

Announcement post

* [x] Draft **✅  see https://docs.google.com/document/d/131PrBIBmBA5fzxGwgPhM_sNdUtHeFDq0AVIPhT_6BTw/edit# gdoc **
* [ ] Life Itself announce
  * [ ] ⏫ Put up the draft as a post (schedule for 16 March)
    * [ ] Find image originals (undraw, coggle etc), download high quality images, upload to cloudinary, embed in post
    * [ ] Set featured image
  * [ ] 🔽 Back post about original launch in Jan using current content of lifeitself.us/web3/
* [x] Publishing an intro piece on Emerge announcing the initiative **✅ Scheduled for 16 March**

Sharing

* [ ] Blurbs drafted
  * [ ] Tweet length (1-3 verions would be good)
  * [ ] Title / Sentence blurb
  * [ ] Paragraph
  * [ ] Image (preferably this could be also the default social media image for the project)
* [ ] Draft for an email
  * [ ] Short lead in / call to action
  * [ ] About the project (below the signature) 
* [ ] Identify good online fora to share in @rufuspollock 

Misc

* [ ] Update current web3 page to redirect or point to new site

## Places to share

Life Itself

* [ ] Twitter
  * [ ] forlifetiself
  * [ ] rufuspollock
  * [ ] liam
* [ ] Facebook
* [ ] Instagram

Other places

- [ ] metamoderna forum
- [ ] emerge network
- [ ] hacker news
- [ ] reddit (buttcoin plus pro forums)
- [ ] people to email (?)

**Comment by nathenf** [comment]
Do you think an Intro video would be useful for this as well? @EilidhRoss1 can basically read the intro and I can cut it into a video. 

Uses:
- Landing video for the youtube channel
- Sharing during the launch
- Easy digestible on the website front page
- Include in the email going out

**Comment by nathenf** [comment]
@rufuspollock I can see the Youtube thumbnails are a different format to the blog post thumbnails. Do you want me to resize them accordingly?

**Comment by rufuspollock** [comment]
> @rufuspollock I can see the Youtube thumbnails are a different format to the blog post thumbnails. Do you want me to resize them accordingly?

Not worth it IMO right now (plus if we do do it, we should just do that via cloudinary API rather than manually)

**Comment by nathenf** [comment]
@rufuspollock the feature image is in the issue description, in case you didn't see it

**Comment by EilidhRoss1** [comment]
@rufuspollock draft copy for the email is in the description

**Comment by nathenf** [comment]
@EilidhRoss1 I have scheduled a twitter post for 7pm your time for the launch. I will be off by then so if the launch is not ready please can you remember to reschedule?

**Comment by theo-cox** [comment]
FIXED. We announced and listed on our newsletter and shared across all named forums. Further digging for places to share wasn't deemed a good use of time.
