### ISSUE TITLE
[epic] Guide to web3 & crypto (v1) 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#77]
Guide to web3 and crypto v1. https://web3.lifeitself.us/guide

---

# Plan

https://coggle.it/diagram/YidoEewvuAnxT9LA/t/web3-crypto-guide-toc

<img width="988" alt="image" src="https://user-images.githubusercontent.com/180658/158962512-c94f10c4-741f-4701-b588-f80a148342e2.png">

## Tasks

* [ ] Convert to bullet points in this issue (as coggle probably not needed here so let's just have this as a set of bullet points)
* [ ] Review current guide against this (as of 18 March)
* [ ] Clarify some items e.g. what is gritty concepts
* [ ] Clarify whether some parts belong in guide e.g. latest events

**Comment by theo-cox** [comment]
WONTFIX. Taking approach outlined in #181 instead.
