### ISSUE TITLE
Set page titles

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#82]
At the moment we are **not** setting the page titles of any pages - it is always the same.

## Acceptance

* [ ] Title of https://web3.lifeitself.us is 'Home | {whatever the siteConfig.title is}` where `{whatever the siteConfig.title is}` is current `Making Sense of Crypto and Web3`
* [ ] Title of e.g. https://web3.lifeitself.us/guide is `Guide | ...`
* [ ] Title of https://web3.lifeitself.us/concepts/ethereum is `Ethereum | ...`
* [ ] Title of https://web3.lifeitself.us/notes/are-crypto-tokens-securities is `Are Crypto Tokens Securities? | ...`
* [ ] You get the idea

## Tasks

* [x] Add titles to pages using slug. 
    * [ ] ( frontmatter/meta doesn't exist for mdx pages for now. If implemented, will need to add frontmatter data for every md page. Do we need this ?

**Comment by Pooreffects** [comment]
I would like to work on this issue.

**Comment by rufuspollock** [comment]
@Pooreffects 👏 please dive in ... and just re-assigned you. You can submit a PR directly or make suggestions here first.

**Comment by rufuspollock** [comment]
@Pooreffects looks like someone got there first - love to have your help on other issues 😄
