### ISSUE TITLE
Video component for displaying youtube videos

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#88]
YouTube component for displaying youtube videos.

See e.g. for https://web3.lifeitself.us/notes/are-crypto-tokens-securities where atm we just have the link.

What i want is:

```
<YouTube src='...' />
```

And this results in a nice responsive display via iframe or whatever - see e.g. https://www.themes.dev/blog/easily-embed-responsive-youtube-video-with-tailwind-css/

## Acceptance

* [ ] Research options and preferably use e.g. https://github.com/video-react/video-react 2.3k⭐ or https://github.com/cookpete/react-player 6.7k⭐
* [ ] Simple YouTube component with argument of youtube url (might need to parse that to get id ...)
* [ ] Way that this automatically provided to all markdown pages without having to explicitly import
  * [ ] Though could explicitly import on first example to test it out

## Tasks

* [ ] ...

**Comment by sdiehl** [comment]
In theory if we can figure out a way to pass-thru raw HTML, all of the YouTube videos are already embedded on the episode notes pages. Remark is just stripping the HTML away at the top because it can't parse it or something. Don't know if there's some setting to allow this or not. 

https://github.com/life-itself/web3/blob/main/notes/post-state-technocracy.md
