### ISSUE TITLE
Show notes for first 3-4 episodes of deep dive are up

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#92]
I suggest we get one fairly polished including front matter structure e.g. https://web3.lifeitself.us/notes/are-crypto-tokens-securities and then do the rest (though can prep the markdown for the others)

## Acceptance

* [x] Episode 1 on neo-metallism **https://web3.lifeitself.us/notes/neo-metallism**
	* [x] Page up with decent slug/url and title
	* [x] Show notes **Done with tidied version. Still some todos especially to update critique**
	* [x] YouTube video
	* [x] Podcast 
* [x] Episode 2 - trader ideology
	* [x] Page up 
	* [x] Fix the youtube embed
	* [x] Podcast links
	* [x] Show notes **Done with somewhat tidied version ~rufus**
* [x] Episode 3 - securities **https://web3.lifeitself.us/notes/are-crypto-tokens-securities** 
	* [x] Page up **✅**
* [x] Episode 4 - ditto

FUTURE: (separate issue?)

* [ ]  set these up so we can feature them onto the front page automatically.

## Tasks

...

## Notes

Imagined frontmatter:

```
title:
description: # short description e.g. for use on front page or in meta
image: # image for use on front page and as page featured image
youtube: # youtube url - may not need this
date: # published date
authors: # array of strings e.g. [ 'Joe Doe', 'Jane Smith']
```

**Comment by sdiehl** [comment]
I think the securities one is a great one to polish if we want to target more of the policy maker audience. I think that one is probably the most relevant for them and our script has some really great talking points in it i we expand it out.

**Comment by rufuspollock** [comment]
@EilidhRoss1 great work 👏

A minor thing: when you close can you add a note as per https://tao.lifeitself.us/issues/#closing-issues 🙂 🙏

Also can you update the description especially the acceptance items as per https://tao.lifeitself.us/issues/#completing-tasks

**Comment by EilidhRoss1** [comment]
@rufuspollock thanks for flagging, noted and will do in future 👍

**Comment by rufuspollock** [comment]
@EilidhRoss1 ok and could you do it on this one - you can still add the comment and update the description.

**Comment by rufuspollock** [comment]
@EilidhRoss1 could you add updates on the tasks in the description with links e.g. see how the first task has the link to the show notes.

This is really helpful for me or any viewer as i can quickly follow the links to the result and have a look

**Comment by EilidhRoss1** [comment]
@rufuspollock sorry, I did this yesterday, I must not have committed the changes properly. Sorry, will do now.
