### ISSUE TITLE
Content Layer abstraction and replacement for next/mdx

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#94]
Replace next/mdx and file based routing for markdown (wiki) content with a new content layer API based on https://github.com/contentlayerdev/contentlayer so that ...

Better markdown parsing

* can use frontmatter again so that e.g.
  * we can e.g. youtube frontmatter and pull it out for front page
  * showing authors
  * sorting by diff types of page
* we can use mdx in markdown w/o `.mdx` extension

We get a "content layer" API that allows us to ...

* search for all concept pages at once so that we can list them easily
* create a network map of concepts (?)

## Acceptance

* [x] rendering all markdown files via a content layer system rather than next/mdx
* [ ] index page for all "wiki" pages (?) at e.g. `/all/`
* [ ] index page for concepts

## Tasks

* [x] Create a `site/content` directory
* [x] Add contentlayer.dev modelling with a generic catch-all
* [x] Add catch-all nextjs route i.e. `pages/[...slug].js`
* [x] Move content over
	* [x] *.md
	* [x] concepts symlink
	* [x] claims symlink
	* [x] notes symlink
	* [x] guide symlink
* [x] Fix titles
* [ ] Create index page for all content
* [ ] Create index page for concepts

## Notes

Khalil notes

- contentlayer.dev seems like a good approach.
- Looks like there is one directory source for local files. Maybe would have to implement a workaround for that so that …
  - why do we need a workaround?). ✅ For the moment we are getting the data from the same repo. If we need to pull content from other repos? Why would we need to get data from other repos? (I can imagine situations of course). At the moment we don’t have that need …
  - What we do have is content in different directories. We solve this by symlinking them into a common directory called "content" or "data" e.g. symlink /claims => site/content/claims
  - Depends on what will be future content sources. Headless cms? Who knows … YAGNI
- Any roadblocks faced when implementing for pages.datahub.io? No big ones.
